# Generated by Django 4.1.1 on 2022-11-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAuthTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('key', models.CharField(default='createstaffuser', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
