# Generated by Django 4.1.1 on 2022-10-25 16:01

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import waterpark.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiket_slug', models.SlugField(unique=True)),
                ('date_of_purchase', models.DateTimeField(default=django.utils.timezone.now)),
                ('validity_day', models.DateField(default=datetime.date.today, help_text='Choose the day you will come to Waterland', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)], verbose_name='Entry Waterland date')),
                ('cost', models.IntegerField(default=15)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonpass_slug', models.SlugField(unique=True)),
                ('date_of_purchase', models.DateTimeField(default=django.utils.timezone.now)),
                ('validity_from', models.DateField(default=datetime.date.today)),
                ('validity_to', models.DateField(default=datetime.date(2023, 1, 1))),
                ('seasonpass_photo', models.ImageField(help_text='Add your photo, it shall added to your season pass', upload_to=waterpark.models.media_directory_path, verbose_name='SeasonPass Photo')),
                ('cost', models.IntegerField(default=125)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SeasonPass',
            },
        ),
    ]
